name: Resume.md to Resume-JohnWhately.pdf

on: 
  push:
  repository_dispatch: #on commit, in the private repo storing .md, run git action with ping to this action call run build.

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    env:
      PandocOutputFilename: Resume-JohnWhately.pdf
      PandocInputFilename: Resume.md #if changed, PrivateRepoMD will also need to be changed to equivilate
      PandocInputFormat: gfm # gfm = github markdown format
      Gfont: noto-fonts   #font name on github repo
      GFontAUX: NotoSans #font name on file
      GFontDir: archive/hinted/NotoSans #git directory to fonts 
      GfontMain: Regular
      GfontBold: Bold
      GfontItalic: Italic
      GfontBoldItalic: BoldItalic
      PrivateRepo: GeoDerp/MyResume #repo where you store your Resume.md
      PrivateRepoMD: /Resume/Resume.md #directory in repo to .md assuming .md is Resume.md
    steps:
      - uses: actions/checkout@v2
        with: 
          repository: ${{ env.PrivateRepo }}
          token: ${{ secrets.ACCESS_TOKEN }}
      - run: |
         mkdir -p output
         cp "$(pwd)"${{ env.PrivateRepoMD }} output/Resume.md
      - name: Build custom Pandoc Docker Container
        run:  echo -e 'FROM pandoc/latex:2.9\n
          RUN apk add --no-cache git\n
          RUN mkdir -p ~/.fonts/${{ env.Gfont }}\n
          RUN git clone https://github.com/googlefonts/${{ env.Gfont }}.git\n
          RUN cp ${{ env.Gfont }}/${{ env.GFontDir }}/* ~/.fonts/${{ env.Gfont }}\n
          RUN fc-cache -f -v\n
          RUN apk add texmf-dist-latexextra\n
          RUN tlmgr install adjustbox babel-german background bidi collectbox csquotes everypage filehook footmisc footnotebackref framed fvextra letltxmacro ly1 mdframed mweights needspace pagecolor sourcecodepro sourcesanspro titling ucharcat ulem unicode-math upquote xecjk xurl zref\n
          ' | docker build -t custompandoclatex -
      - name: run custom docker container 
        run: >-
          docker run -v "$(pwd)"/output:/output:z custompandoclatex
          --output=/output/${{ env.PandocOutputFilename }}
          --pdf-engine=xelatex
          --template https://raw.githubusercontent.com/GeoDerp/pandoc-latex-template/master/eisvogel.tex
          --listings
          -V geometry:margin=0.5in
          -V 'mainfont:${{ env.GFontAUX }}-${{ env.GfontMain }}'
          -V 'mainfontoptions:BoldFont=${{ env.GFontAUX }}-${{ env.GfontBold }}, ItalicFont=${{ env.GFontAUX }}-${{ env.GfontItalic }}, BoldItalicFont=${{ env.GFontAUX }}-${{ env.GfontBoldItalic }}'
          -V urlcolor=blue
          -V disable-header-and-footer=true
          -f ${{ env.PandocInputFormat }}
          /output/${{ env.PandocInputFilename }}
      - uses: actions/upload-artifact@master
        with:
          name: output
          path: output/${{ env.PandocOutputFilename }}
